export const DataType = {
	SIMCONNECT_DATATYPE_INVALID: 0,
	SIMCONNECT_DATATYPE_INT32: 1,
	SIMCONNECT_DATATYPE_INT64: 2,
	SIMCONNECT_DATATYPE_FLOAT32: 3,
	SIMCONNECT_DATATYPE_FLOAT64: 4,
	SIMCONNECT_DATATYPE_STRING8: 5,
	SIMCONNECT_DATATYPE_STRING32: 6,
	SIMCONNECT_DATATYPE_STRING64: 7,
	SIMCONNECT_DATATYPE_STRING128: 8,
	SIMCONNECT_DATATYPE_STRING256: 9,
	SIMCONNECT_DATATYPE_STRING260: 10,
	SIMCONNECT_DATATYPE_STRINGV: 11,
	SIMCONNECT_DATATYPE_INITPOSITION: 12,
	SIMCONNECT_DATATYPE_MARKERSTATE: 13,
	SIMCONNECT_DATATYPE_WAYPOINT: 14,
	SIMCONNECT_DATATYPE_LATLONALT: 15,
	SIMCONNECT_DATATYPE_XYZ: 16,
} as const;

export type DataType = (typeof DataType)[keyof typeof DataType];
