/**
 * https://docs.flightsimulator.com/html/Programming_Tools/SimConnect/API_Reference/Structures_And_Enumerations/SIMCONNECT_SIMOBJECT_TYPE.htm
 */
export enum SIMCONNECT_SIMOBJECT_TYPE {
	SIMCONNECT_SIMOBJECT_TYPE_USER,
	SIMCONNECT_SIMOBJECT_TYPE_ALL,
	SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT,
	SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER,
	SIMCONNECT_SIMOBJECT_TYPE_BOAT,
	SIMCONNECT_SIMOBJECT_TYPE_GROUND,
}
